name: Weekly Netflix Data Fetch + Deduplication

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 06:00 UTC
  workflow_dispatch:     # Allow manual triggering too

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip

    - name: Run fetch_netflix_data.py
      run: python scripts/fetch_netflix_data.py

    - name: Run deduplicate_netflix_data.py
      run: python scripts/deduplicate_netflix_data.py

    - name: Commit and push if changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add netflix_data.json
        git diff --cached --quiet || git commit -m "🗂 Weekly update: fetched & deduplicated Netflix data"
        git push
