name: Test old pipeline (no commit)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests imdbpy
          fi

      - name: Run your original scripts (no commit)
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          TRAKT_CLIENT_SECRET: ${{ secrets.TRAKT_CLIENT_SECRET }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
        run: |
          set -e
          python -u fetch_netflix_data.py
          if [ -f fetch_imdb_rating.py ]; then python -u fetch_imdb_rating.py || true; fi
          python -u deduplicate_netflix_data.py

      - name: Summarize outputs
        run: |
          python - << 'PY'
          import json, os, sys
          for f in ["netflix_data.json","netflix_last_month.json","netflix_data_partial.json"]:
              if os.path.exists(f):
                  try:
                      data=json.load(open(f, encoding="utf-8"))
                      print(f"{f}: {len(data)} items")
                  except Exception as e:
                      print(f"{f}: ERROR {e}")
              else:
                  print(f"{f}: not found")
          PY
