name: Update & Deploy Data (orig pipeline)

on:
  schedule:
    - cron: "0 4 * * 1"   # wekelijks: ma 06:00 Europe/Brussels ≈ 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-data
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests imdbpy

      # ---- JOUW ORIGINELE PIPELINE ----
      - name: Fetch Netflix data (TMDb + IMDb/Trakt via jouw script)
        run: python -u fetch_netflix_data.py

      - name: (Optioneel) Extra IMDb verrijking
        run: |
          if [ -f fetch_imdb_rating.py ]; then python -u fetch_imdb_rating.py || true; fi

      - name: Deduplicate
        run: python -u deduplicate_netflix_data.py

      # --- Inspectie: toon of JSON's gewijzigd zijn
      - name: Show JSON hashes
        run: |
          for f in netflix_data.json netflix_last_month.json; do
            if [ -f "$f" ]; then
              echo "$f  ->  $(sha256sum "$f" | cut -d' ' -f1)"
            else
              echo "$f not found"
            fi
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git rebase origin/main || git rebase --abort || true
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update data [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
