name: Update & Deploy Data

on:
  schedule:
    - cron: "0 4 * * 1"   # wekelijks: ma 06:00 Europe/Brussels ≈ 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-data
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update all JSONs
        env:
          UNOGS_API_KEY: ${{ secrets.UNOGS_API_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          REQUIRE_TMDB_PROVIDER_CHECK: "0"
        run: python -u update_all.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git rebase origin/main || git rebase --abort || true
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Update data [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
